### ISSUE TITLE
Monad syntax in Raku

### ISSUE THREAD

**Issue by arunvickram** [masukomi/Definitely#4]
I've been wanting to make an issue a regarding this because I've been thinking about how Raku could accomplish this, but I'm not sure if this is the best place to do it.

I was wondering what Haskell's do notation would potentially look like in Raku, because I generally think it is possible to replicate it, be it with slangs (i'd rather have this be a last resort though).

F#'s computation expressions are basically monad syntax

```fsharp
let fetchAndDownload url =
    async {
        let! data = downloadData url

        let processedData = processData data

        return processedData
    }
```

I'm wondering what this could look like in Raku though.

Just some food for thought.

**Comment by librasteve** [comment]
hi arun - I think that your suggestion is very interesting, but I do not really see how it would be applied to this module

appreciate the food for thought ... maybe this is due to my poor understanding of what the F# code is doing...
